Thomas Wilson Chunk #1
friends-library/thomas-wilson pull request #2
Opened 2019-03-22 19:53 UTC by Henderkiah

@jaredh159 @Henderjay

2019-03-26 13:55 UTC, Henderjay requested changes
Really good work, Kiah. The main things I want you to change here are to remove most of the asterisms (where marked), and to change some of the headings (that I might have told you wrong).  But none of these things are really _mistakes_... they are just things you need to learn.  You did a really good and careful job! Fix the stuff I marked, and I'll merge it.  Oh... and come up to my office to have me explain to you how we use the asterisms in these final copies.👍🏻

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/03-epistles.adoc
>  == Epistles Written by Thomas Wilson, And His Fellow-Laborer in the Service of the Gospel, James Dickinson, While in America.
This chapter heading is too long for it to fit as a "header" on a book page. So you need to make a shortened version, maybe to _Epistles of Thomas Wilson and James Dickinson_ . To do this, look under the Short Titles section on the style guide.👍🏻

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/04-testimonies.adoc
>  '''
I think we can remove this asterism here. Come up to my office and I'll try to explain when we keep, and when we kill the asterisms.

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/04-testimonies.adoc
>  [.asterism]
I think we can kill this one too.

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/04-testimonies.adoc
>  [.asterism]
and this one

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/04-testimonies.adoc
>  [.asterism]
kill this one too.

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/03-epistles.adoc
> +[.chapter-subtitle--blurb]
I think I told you wrong on this.  Sorry!!! I think this the remaining letter headings in this chapter should be just `[.blurb]` tags, and not `[.chapter-subtitle-blurb]`

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/03-epistles.adoc
> +[.chapter-subtitle--blurb]
so make this one a `[.blurb]` too

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/03-epistles.adoc
> +[.chapter-subtitle--blurb]
just blurb here too.

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/03-epistles.adoc
> +[.chapter-subtitle--blurb]
and just blurb here.

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/03-epistles.adoc
> +[.chapter-subtitle--blurb]
and blurb here.

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/04-testimonies.adoc
>  [.asterism]
you can kill this asterism

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/04-testimonies.adoc
>  [.asterism]
and kill this one

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/04-testimonies.adoc
>  [.asterism]
and kill this one

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/04-testimonies.adoc
>  [.asterism]
and kill this one

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/04-testimonies.adoc
>  [.asterism]
and kill this one

2019-03-26 13:55 UTC, Henderjay commented on journal-letters/modernized/04-testimonies.adoc
>  [.asterism]
and kill this one

2019-03-26 14:01 UTC, Henderkiah commented
Okay, I’ll come up soon!

-Kiah

From: Jason
Sent: Tuesday, March 26, 2019 9:55 AM
To: friends-library/thomas-wilson
Cc: Henderkiah; Author
Subject: Re: [friends-library/thomas-wilson] Thomas Wilson Chunk #1 (#2)

@Henderjay requested changes on this pull request.
Really good work, Kiah. The main things I want you to change here are to remove most of the asterisms (where marked), and to change some of the headings (that I might have told you wrong). But none of these things are really mistakes... they are just things you need to learn. You did a really good and careful job! Fix the stuff I marked, and I'll merge it. Oh... and come up to my office to have me explain to you how we use the asterisms in these final copies.👍🏻

In journal-letters/modernized/03-epistles.adoc:
> @@ -1,8 +1,13 @@

 == Epistles Written by Thomas Wilson, And His Fellow-Laborer in the Service of the Gospel, James Dickinson, While in America.

This chapter heading is too long for it to fit as a "header" on a book page. So you need to make a shortened version, maybe to Epistles of Thomas Wilson and James Dickinson . To do this, look under the Short Titles section on the style guide.👍🏻

In journal-letters/modernized/04-testimonies.adoc:
> @@ -95,11 +96,13 @@ and touch the tongues of many of our youth, with a live coal from his holy altar

 that many may be willing to run his errand, and be serviceable in his hand,

 as were many of the generation, whom he has removed from us.

 

-Mary Wilson.

+[.signed-section-signature]

+Mary Wilson

 

 [.asterism]

 '''

I think we can remove this asterism here. Come up to my office and I'll try to explain when we keep, and when we kill the asterisms.

In journal-letters/modernized/04-testimonies.adoc:
>  

+[.signed-section-context-close]

 Thornwell, the 1st of the Third month, 1727.

 

 [.asterism]

I think we can kill this one too.

In journal-letters/modernized/04-testimonies.adoc:
>  

-James Dickinson.

+[.signed-section-signature]

+James Dickinson

 

 [.asterism]

and this one

In journal-letters/modernized/04-testimonies.adoc:
>  Joshua Clibborn, John Barclay, Mungo Bewley, Gregory Russel, Joseph Inman, John Stoddart,

 Jonathan Robinson, Edward Barwick, Joseph Gill, John Boles, Richard Sealey,

 Abel Strettel, Thomas Ducrett, Solomon Watson, Ralph Stephenson, Samuel Watson,

-Nicholas Harris, James Pillar, Bartho.

-Garnett, Thomas Greer, James Hill, Daniel Bewley, Toby Courtney, Samuel Fuller,

-John Chrysty.

+Nicholas Harris, James Pillar, Bartho Garnett, Thomas Greer, James Hill, Daniel Bewley,

+Toby Courtney, Samuel Fuller, John Chrysty.

 

 [.asterism]

kill this one too.

In journal-letters/modernized/03-epistles.adoc:
>  Thomas Wilson, James Dickinson.

 

-=== An Epistle to Friends in Pennsylvania.

+[.chapter-subtitle--blurb]

I think I told you wrong on this. Sorry!!! I think this the remaining letter headings in this chapter should be just [.blurb] tags, and not [.chapter-subtitle-blurb]

In journal-letters/modernized/03-epistles.adoc:
>  From Rhode Island, the 5th of the Fifth month, 1692.

 

-=== An Epistle to Friends in Barbados and Elsewhere.

+[.chapter-subtitle--blurb]

so make this one a [.blurb] too

In journal-letters/modernized/03-epistles.adoc:
>  From Antigua, the 14th of the Tenth month, 1692.

 

-=== An Epistle to Friends in Philadelphia.

+[.chapter-subtitle--blurb]

just blurb here too.

In journal-letters/modernized/03-epistles.adoc:
>  Nevis, the 4th of the Twelfth month, 1692-3.

 

-=== Another Epistle to Friends in America.

+[.chapter-subtitle--blurb]

and just blurb here.

In journal-letters/modernized/03-epistles.adoc:
>  Thomas Wilson, James Dickinson.

 

-=== To Friends of Mount-melick, Men`'s Meeting, and Elsewhere.

+[.chapter-subtitle--blurb]

and blurb here.

In journal-letters/modernized/04-testimonies.adoc:
> @@ -406,6 +418,7 @@ to the refreshing and edifying of Friends.

 [.asterism]

you can kill this asterism

In journal-letters/modernized/04-testimonies.adoc:
> @@ -445,6 +458,7 @@ wherein the Lord blessed his endeavors with prosperity and plenty.

 [.asterism]

and kill this one

In journal-letters/modernized/04-testimonies.adoc:
> @@ -465,6 +479,7 @@ have been given forth in the wisdom of truth.

 [.asterism]

and kill this one

In journal-letters/modernized/04-testimonies.adoc:
> @@ -515,6 +530,7 @@ Samuel Peacock, John Scott.

 [.asterism]

and kill this one

In journal-letters/modernized/04-testimonies.adoc:
> @@ -591,9 +607,10 @@ Nathan Newby.

 [.asterism]

and kill this one

In journal-letters/modernized/04-testimonies.adoc:
>  

+[.signed-section-context-close]

 Mosedale, in Cumberland, the 28th of the Third month, 1726.

 

 [.asterism]

and kill this one
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-03-27 19:37 UTC, Henderjay requested changes
The only thing to do is kill your one comment.

2019-03-27 19:54 UTC, merged

2019-03-27 19:54 UTC, Henderjay commented
looks great, merging!!

2019-03-27 19:54 UTC, Henderkiah commented
Okay.

-Kiah

From: Jason
Sent: Wednesday, March 27, 2019 3:54 PM
To: friends-library/thomas-wilson
Cc: Henderkiah; Author
Subject: Re: [friends-library/thomas-wilson] Thomas Wilson Chunk #1 (#2)

looks great, merging!!
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.